data:
     image: debian:8
     volumes:
      - ~/Docker/data:/var/lib/mysql
mysql:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: laye
     volumes_from:
       - data
site:
    build: Docker_client
    command: /usr/bin/supervisord 
    ports:
     - "8080:8080"
    cap_add:
      - ALL
    links:
     - mysql:mysql
    labels:
     - "nature=application"
