data:
     image: debian:8
     container_name: data
     command: /bin/true
     volumes:
      - ~/Docker/data:/var/lib/mysql
mysql:
     build: Docker_link
     container_name: mysql
     environment:
       MYSQL_ROOT_PASSWORD: laye
       MYSQL_PORT_3306_TCP_ADDR: 172.17.0.2
     volumes_from:
       - data
site:
    container_name: lutece_cont
    build: Docker_client
    command: /usr/bin/supervisord 
    ports:
     - "8080:8080"
    cap_add:
      - ALL
    links:
     - mysql:mysql
    labels:
     - "nature=application"
